### PR TITLE
Future proofing 2

### PR DESCRIPTION
**Pull request by IntangibleTrapazoid**

### CODE REVIEW

**Comment by IntangibleTrapazoid** [comment]
As i am a complete noob i dont know how to combine my two pull requests into one so they are two pull requests with basically the same purpose.

**Comment by noahcoolboy** [comment]
What exactly does this do

**Comment by IntangibleTrapazoid** [comment]
I dont know why there were so many edits but i reverted them so you can look at the one on the bottom to see what is changed.

Basically i just changed it to a non static number for future proofing

**Comment by noahcoolboy** [comment]
What your modifications do is to use the length of "Win32" (5 characters) instead of the constant number 7
This means that the Math.random wouldn't be able to range the full array
This is no fix or future proofing, all it does is break stuff

**Pull request closed without merging**
